---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: docker
      path: eve/workers/unit_and_feature_tests
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: npm install
          command: npm install
      - ShellCommand:
          name: run static analysis tools on markdown
          command: npm run lint_md
      - ShellCommand:
          name: run static analysis tools on code
          command: npm run lint
