---
name: tests

on:
  push:
    branches-ignore:
    - 'development/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: lint markdown
      run: yarn lint_md
    - name: lint javascript
      run: yarn lint
