---
name: tests

on:
  push:
    branches-ignore:
    - 'development/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '8'
    - name: install dependencies
      run: npm install
    - name: lint markdown
      run: npm run lint_md
    - name: lint javascript
      run: npm run lint
